### ISSUE TITLE
Running insert_urls deleted part of golden.csv file

### ISSUE THREAD

**Issue by peter-dimitrov** [mikeizbicki/metahtml#104]
I ran

```
python3 tests/test_golden.py --insert_urls https://www.eurosport.fr/football/equipes/al-jihad/teamcenter.shtml
```

on this url and it displayed this error:

```
WARNING: overwriting url= https://www.eurosport.fr/football/equipes/al-jihad/teamcenter.shtml
Traceback (most recent call last):
  File "tests/test_golden.py", line 393, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 245, in insert_golden_tests
    writer.writerow(row)
  File "/usr/lib/python3.6/csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib/python3.6/csv.py", line 151, in _dict_to_list
    + ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: None
```

 When I went back to golden.csv, all of the urls below this url were deleted. Is there any way to undo this? Or otherwise stop it from happening in the future? Thanks

![image](https://user-images.githubusercontent.com/56900637/87601682-8d506500-c6c3-11ea-825d-94dd545c2bcb.png)

**Comment by mikeizbicki** [comment]
I've had that happen to me.  I thought I fixed it, but I guess not completely.  I'll look into it again.

There's no way to undo it unfortunately.

**Comment by peter-dimitrov** [comment]
OK, please let me know when you do because I was going back through everything and it happened again unfortunately

**Comment by mikeizbicki** [comment]
It's not going to be anytime soon.  The easy work around is to just always copy the file somewhere else so you have a backup, or to leave the file open in libreoffice so that even if it gets overwritten, you can just press save and it will write the correct thing back.

**Comment by peter-dimitrov** [comment]
Since I have to use the lambda server I can't open the golden.csv file except in vim, so how do I copy the contents of golden.csv in vim so that I can then paste it into a libreoffice file and save it separately? I have tried gg+"yG and it said all of the lines have been yanked but I am then unable to paste them anywhere.

**Comment by mikeizbicki** [comment]
Just leave the vim window open and run the commands in a different terminal. 
Then if the file gets overwritten, you can just save it again.

**Comment by peter-dimitrov** [comment]
Ok, that worked to keep the file from being overwritten, but at this point every URL I try to add throws up this error. I don't know why this started happening now, but it's making it impossible to make any progress.
