### ISSUE TITLE
Working on week 6 urls before my week 5 url pull request is merged

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#105]
I submitted a pull request with my work for week 5 urls but I don't want to start working on week 6 urls yet as I likely will have to refork your repository. Is there a way around this? I can also wait for you to merge the pull request and I can finish week 6 tomorrow and into the weekend. Thanks!

**Comment by mikeizbicki** [comment]
I'm not sure when I'm going to have a chance to review your week5, so go ahead and start doing week6 based off of your latest commit for week5.

**Comment by rayegleekel** [comment]
Should I add another commit for my week 6 urls and create another pull request from my latest commit? Or should I amend my week5 url commit to include my work for week 6?
