### ISSUE TITLE
Time tomorrow

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/metahtml#106]
Hi Professor Izbicki, 

Do you have any time tomorrow before 10, between 11-2 or after 4? I have a few questions :)

Take care,
Maxinen

**Comment by mikeizbicki** [comment]
I'm sorry, I'm just now seeing this.  I'm free Monday after about 2.  Would that work?

**Comment by maxinebaghdadi** [comment]
Sure, does 2:30 work?
