### ISSUE TITLE
TypeError when running the command to generate the test cases

### ISSUE THREAD

**Issue by shashankvineet** [mikeizbicki/metahtml#11]
When I run the following command:

```$ python3 tests/test_golden.py --insert_urls https://www.theguardian.com/world/2020/apr/21/north-korean-leader-kim-jong-un-has-heart-surgery-report```

I get the following error (I'm not sure why they are giving 404 errors because when I open the links in the browser, they seem to exist): 

```
downloading url= https://www.theguardian.com/world/2020/ ... error: status_code= 404
downloading url= https://www.theguardian.com/world/2020/apr/ ... error: status_code= 404
downloading url= https://www.theguardian.com/world/2020/apr/21/ ... done.
Traceback (most recent call last):
  File "tests/test_golden.py", line 359, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 146, in insert_golden_tests
    if row['url']==url or row['url']==url+'/' or row['url']+'/'==url:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by mikeizbicki** [comment]
Based on your formatting, I can't tell what the command is that you actually typed in.

**Comment by shashankvineet** [comment]
I'm sorry, I think it should be correct now.

**Comment by mikeizbicki** [comment]
I get 404 errors when I open those links in the browser too, so I think that's correct.

The command works fine for me.  My guess is that your shell is somehow interpreting some of the characters in the parameter string before passing them into the python code.  The fix would be to put the url in single quotes `'like this'`, or to use the bulk loading method in the README that will load all of the urls in a file (search the page for `xargs` to find the command).

**Comment by shashankvineet** [comment]
I tried the bulk loading method with the following command:

```
cat urls/week1-shashank | xargs python3 tests/test_golden.py --insert_urls
```

but it gives me multiple errors:

``` 
downloading url= http://112.international/ ... Traceback (most recent call last):
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='112.international', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/test_golden.py", line 359, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 138, in insert_golden_tests
    get_cached_webpages(new_url,None)
  File "tests/test_golden.py", line 91, in get_cached_webpages
    download_url()
  File "tests/test_golden.py", line 80, in download_url
    r = requests.get(url,headers={'User-Agent':'NovichenkoBot'})
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='112.international', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
```

**Comment by shashankvineet** [comment]
I tried running it with the single quotes, but it still gives me the same error:

```
Traceback (most recent call last):
  File "tests/test_golden.py", line 359, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 146, in insert_golden_tests
    if row['url']==url or row['url']==url+'/' or row['url']+'/'==url:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by shashankvineet** [comment]
> I tried the bulk loading method with the following command:
> 
> ```
> cat urls/week1-shashank | xargs python3 tests/test_golden.py --insert_urls
> ```
> 
> but it gives me multiple errors:
> 
> ```
> downloading url= http://112.international/ ... Traceback (most recent call last):
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
>     cnx.do_handshake()
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
>     self._raise_ssl_error(self._ssl, result)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
>     _raise_current_error()
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
>     raise exception_type(errors)
> OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
>     self._validate_conn(conn)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
>     conn.connect()
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
>     ssl_context=context)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
>     raise ssl.SSLError('bad handshake: %r' % e)
> ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='112.international', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tests/test_golden.py", line 359, in <module>
>     insert_golden_tests(urls, args.overwrite, args.verbose)
>   File "tests/test_golden.py", line 138, in insert_golden_tests
>     get_cached_webpages(new_url,None)
>   File "tests/test_golden.py", line 91, in get_cached_webpages
>     download_url()
>   File "tests/test_golden.py", line 80, in download_url
>     r = requests.get(url,headers={'User-Agent':'NovichenkoBot'})
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
>     return request('get', url, params=params, **kwargs)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 640, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 640, in <listcomp>
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 218, in resolve_redirects
>     **adapter_kwargs
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/Users/shashankvineet/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='112.international', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
> ```

**Comment by shashankvineet** [comment]
I tried fixing the bulk loading method by doing the following change in line 80 of the test_golden.py file :

```
 r = requests.get(url,headers={'User-Agent':'NovichenkoBot'}, verify=False)
```

This helped me bypass the SSLErrors, but it still gives me the same TypeError from before:

```
downloading url= http://112.international/article/ ... error: status_code= 404
Traceback (most recent call last):
  File "tests/test_golden.py", line 358, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 145, in insert_golden_tests
    if row['url']==url or row['url']==url+'/' or row['url']+'/'==url:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by mikeizbicki** [comment]
Hmm... I'm not sure what's going on since it's working fine on my end.  I can do a zoom call tomorrow (Tuesday) at either 1pm or 8pm, or Wednesday I'd be free anytime after 10am.

**Comment by shashankvineet** [comment]
I can do a zoom call tomorrow at 1pm.

**Comment by mikeizbicki** [comment]
Ok, see you then.

**Comment by selina-28030** [comment]
Hi Professor Izbicki,
Are you still available for a zoom call right now?

**Comment by mikeizbicki** [comment]
Yes, I'm on zoom right now.
