### ISSUE TITLE
Committing my week 6 urls

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#110]
I commented this on a closed issue but I am not sure you get alerted when issues are closed. Should I do a new commit for my week 6 url work and make another pull request off that? Or should i amend my last commit? 

Also, there are two urls in my week 6 that I can't get the path for. I have no idea why because the information isn't stored in any where complex but for some reason nothing I do pulls them. Should I manually input the data so they fail the test case or would you want to zoom today to try to see what is going on? 

Thanks!

**Comment by mikeizbicki** [comment]
You should do a separate pull request based off of the new code, not your
existing pull request.

Note that pull requests are attached to each branch of a repo, so if you make
any changes to the repo (for example by deleting a branch), it will make the
corresponding change to the pull request.

As for the urls that you can't get the data for, my guess is that the data is
loaded dynamically via javascript, and so doesn't actually exist in the
downloaded cache file.  Just manually enter them so they fail the test case, and
I'll look at it when I merge the request.

Also, I should have time to merge your pull request this afternoon.

**Comment by rayegleekel** [comment]
Okay! I just committed my new changes for week 6 url work and went to make a pull request and it won't let me make a new one and just shows me my week 5 url pull request. Should I delete that pull request and just make a new one incorporating both week 5 and week 6 work? Thank you!
