### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#114]
When I run ```python3 tests/test_golden.py --insert_urls```, I get the error message: 

```
Traceback (most recent call last):
  File "tests/test_golden.py", line 22, in <module>
    import metahtml.timestamp
  File "./metahtml/__init__.py", line 7, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'
```
Do I need to import a package? Thanks!

**Comment by mikeizbicki** [comment]
If you run `pip3 install -r requirements.txt` you'll get all the packages needed.

**Comment by rayegleekel** [comment]
When I run that I am getting the message:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Any idea why? Thanks!
________________________________

**Comment by rayegleekel** [comment]
Never mind! I wasn't in the metahtml directory but when I went into it and ran the command it worked. Thanks!
