### ISSUE TITLE
No date and date information stored with other text

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#115]
If URLs have no date info, I have been manually entering them as TRUE,  putting their title and entering my name in ```human_annotator```. Is this what you would still like us to do as opposed to saying ```skip: no date```? I saw some of the entries had this tag so I wanted to double check as a lot of my URLs have this. 

Also, when date information is stored with other text and paths don't seem to work to extract it, should I put ```skip: date parser``` every time and leave all the other columns as they automatically enter?  

Also, what should I put if the day, month and year are all stored in different places so no xpath will work? Thanks!

**Comment by mikeizbicki** [comment]
>If URLs have no date info, I have been manually entering them as TRUE, putting their title and entering my name in human_annotator. Is this what you would still like us to do as opposed to saying skip: no date? I saw some of the entries had this tag so I wanted to double check as a lot of my URLs have this.

Either way is fine.  When I merge your requests, I replace those with `skip: no date`, but you can go ahead and enter that directly too.

> Also, when date information is stored with other text and paths don't seem to work to extract it, should I put skip: date parser every time and leave all the other columns as they automatically enter?

Don't put `skip` for this one, as I want to see how these fail when I do the merge so I can get a sense of what the types of failures here are.

> Also, what should I put if the day, month and year are all stored in different places so no xpath will work? Thanks!

Hmmm... put `skip: date separate locations` for `human_annotator`, and you can leave the rest blank.
