### ISSUE TITLE
Adding pull request for incomplete week5

### ISSUE THREAD

**Issue by peter-dimitrov** [mikeizbicki/metahtml#116]
I'm going to submit a pull request for week5 since I was having the error we talked about a couple of days ago, and the newest version might fix the error. But my timestamp.py file will contain some xpaths that don't work (because I couldn't test them after the first time, or my golden.csv would be wiped). Same story with the golden.csv (some urls that are articles but have invalid xpaths and thus article=FALSE for these). How should I go about dealing with these entries? Should I manually go through the timestamp.py and remove the ones that didn't work? Or is there a better solution?

**Comment by mikeizbicki** [comment]
Yes, you should remove the ones that don't have corresponding entries in the `golden.csv` file.
