### ISSUE TITLE
XPaths Question

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/metahtml#121]
Hi Professor Izbicki,

There are a few x paths that I am struggling with. I've attached the links to the articles below:

1. https://www.culture.leclerc/livre-u/arts-culture--societe-u/sciences-humaines-u/ecologie-et-environnement-u/de-la-menace-terroriste-au-traitement-des-victimes--menace-chimique-bioterrorisme-bombes-sales-nevrose-traumatique-syndrome-de-stockholm-aides-juridiques-9782747547765-pr
2. http://de.danielpipes.org/3550/zu-den-irakischen-massenvernichtungswaffen
3. http://edoc.vifapol.de/opus/volltexte/2007/195/
4. http://ingo-tessmann.de/einstein/node25.html
5. https://www.lejourduseigneur.com/nos-programmes/quelle-place-pour-les-chretiens-dans-lapres-daesh/
6. https://www.palestine-solidarite.org/analyses.abdel_bari-atwan.210119.htm
7. https://plumenclume.org/blog/278-vaccins-le-bioterrorisme-contre-le-tiers-monde
8. https://www.tree2share.org/article-149-bioterrorisme-de-l-utilite-des-pandemies/

Let me know if it's easier to go through them over a call. 

Thanks!
Maxine

**Comment by mikeizbicki** [comment]
I can meet on zoom either Monday or Tuesday at 2pm.  Does that work?
