### ISSUE TITLE
Committing/Pushing week8 work

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#126]
Should we wait to commit and push our week 8 work until you accept the pull requests from last week? I figured there was no rush to commit and push as it was our last week of work and it is simpler if there is only one commit per pull request. But, I can do either! Thanks!

**Comment by mikeizbicki** [comment]
Go ahead and push your week 8 work when you're done.  It'll be easiest for me to do them both at the same time.
