### ISSUE TITLE
Sites can't be reached

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#13]
When I am putting in a lot of the URLs, I am getting "your connection is not private" or "this site can't be reached" warning messages, so my computer won't let me access the URLs. Should I ignore these messages and find a way around it?

**Comment by mikeizbicki** [comment]
This isn't quite enough information for me to help.  Are these messages that your web browser is giving you when you access the urls?  If so, you can ignore the warnings about bad ssl certifications.

If a website doesn't exist though, then you should just skip that url.
