### ISSUE TITLE
can't clone the repo

### ISSUE THREAD

**Issue by ohorban** [mikeizbicki/metahtml#135]
Hi Mike, I am trying to clone the repo and after running the command:
`git sparse-checkout init`
I get this output:
`git: 'sparse-checkout' is not a git command. See 'git --help'.`
I CDed into the directory, so I'm not sure what's the problem

**Comment by mikeizbicki** [comment]
The sparse checkout is a recent git command.  You should either upgrade your git version (I know the latest, git 2.30.0 works, but I believe anything greater than about 2.18 should work), or work on the lambda server (which has the latest git installed).
