### ISSUE TITLE
human_annotator

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/metahtml#16]
HI everyone!

For any url I run with `python3 tests/test_golden.py --insert_urls`, I get the following error:

```
Traceback (most recent call last):
  File "tests/test_golden.py", line 272, in <module>
    @pytest.mark.parametrize('test',get_golden_tests())
  File "tests/test_golden.py", line 264, in get_golden_tests
    valid_annotator = test['human_annotator'] is not None and test['human_annotator'] != 'skip'
KeyError: 'human_annotator'
```
Has anyone come across this same error?

**Comment by mikeizbicki** [comment]
Shashank had a similar error, and the problem ended up being that he had a corrupted line in his `tests/golden.csv` file that he accidentally added while resolving a merge conflict.

**Comment by maxinebaghdadi** [comment]
Hi Professor Izbicki, I don't see anything unusual. But to clarify, should we apply the is_article and download_date columns to the previous data? Perhaps that's what causing the issue?

**Comment by mikeizbicki** [comment]
I don't understand what you mean by "apply is_article and download_date columns to the previous data"?

If you haven't, then you'll need to update your local version of the repository from my repo.  That could also be causing an error like this.

**Comment by maxinebaghdadi** [comment]
I've updated my local version but for some reason what's happened is that everything that was there before has stayed the way it is at the top of the excel sheet. There is then a divider with new headers (including is_article and download_date) along with all the new URLs you've inserted. Do you know how that could have happened?

**Comment by mikeizbicki** [comment]
This sounds like you had an unresolved merge conflict.

I'm on zoom right now if you need help getting this resolved.
