### ISSUE TITLE
Edits to the Hostname List

### ISSUE THREAD

**Issue by WasabiWabiSabi** [mikeizbicki/metahtml#162]
Hey Mike,

I have a small question! There are a couple of newspapers that have gone out of circulation in the hostnames.cvs... should I edit the file and do a pull request? Or leave it be?

Best,
Axel

**Comment by mikeizbicki** [comment]
Good question.

Leave it be.  There's still archived copies of those newspapers floating around and the goal is to be able to work both with currently published papers and archives in order to create a historical record.
