### ISSUE TITLE
Question regarding git pull

### ISSUE THREAD

**Issue by Tonnpo** [mikeizbicki/metahtml#167]
Hi Mike!

After pulling from your master branch via `git pull upstream master`, I am excited to start using your annotating program. However, I am struggling on how to use it. When I ran the command
```
python3 tests/test_content.py --lang=en --username=Tonnpo
```
Since I did not provide the url argument, according to the source code, if I understood it correctly, it should start with the unannotated entity. But I got this error:
```
get_unannotated_urls()
len(urls)=1501
/home/${user}/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'theintercept.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
downloading url= https://theintercept.com/drone-papers/the-kill-chain/ ... r.encoding= utf-8
Traceback (most recent call last):
  File "tests/test_content.py", line 190, in <module>
    run(annotate_content)
  File "/home/${user}/.local/lib/python3.6/site-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/home/${user}/.local/lib/python3.6/site-packages/clize/runner.py", line 363, in run
    ret = cli(*args)
  File "/home/${user}/.local/lib/python3.6/site-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "tests/test_content.py", line 101, in annotate_content
    annotate_content_url(url, username)
  File "tests/test_content.py", line 118, in annotate_content_url
    with open(test_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/${user}/metahtml/tests/.golden/https___theintercept.com_drone-papers_the-kill-chain_14a2839a/2021-07-02'
```
It seems to me that the test path is not correct. Specifically, the date is not supposed to be 2021-07-02. So, I guess that this happens because I do not have the cached file of this webpage in .cache folder. So, I check the .cache directory and there is only this directory (`https___foreignpolicy.com_2013_04_12_the-missile-tests-you-missed-while-watching-north-korea_7d5736f9a049fdfb`) inside .cache. So, I believe my question is how do I pull from your master branch in order to have all directories inside .cache?

Thanks very much in advance!

**Comment by mikeizbicki** [comment]
Likely, you cloned the repo using these instructions to not download all the test cases: https://github.com/mikeizbicki/metahtml#downloading  That's what I recommended before because the test cases take up about 3gb of data.

Now, however, like you noticed, you'll need access to those test cases.  The normal `git clone` command will download the full repo.

**Comment by Tonnpo** [comment]
Cool! thank you.
