### ISSUE TITLE
Issue adding all URLS 

### ISSUE THREAD

**Issue by peter-dimitrov** [mikeizbicki/metahtml#22]
I am trying to insert all of the URLS for this week with this command:
```cat urls/week1-pete | xargs python tests/test_golden.py --insert_urls```
but get this error:
```
Traceback (most recent call last):
  File "tests/test_golden.py", line 362, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 165, in insert_golden_tests
    cache = get_cached_webpages(url,None)
  File "tests/test_golden.py", line 65, in get_cached_webpages
    os.makedirs(url_dir, exist_ok=True)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'tests/.cache\\https___www.chicagotribune.com_nation-world_ct-nw-kim-jong-un-health-north-korea-20200421-wwvgaayf2rgwxhtdlvqcfyvfrm-story.html\r1ebd9646'
```

I am able to add individual URLs, but just not all of them at once. Any ideas how to fix this?

Thanks

**Comment by mikeizbicki** [comment]
Windows has very poor support for the terminal.  So it's possible that command uses several terminal features that might not be support in the shell program you're using.

Or it's possible that there is just one particular url that is causing the problem and that you wouldn't be able to add that one url manually either if you tried to add it by itself.

Either way, you'll probably have to add them manually.
