### ISSUE TITLE
BBC URLs

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#3]
Hi everyone! When I ran the command for the BBC urls, I got 3 entries per URL--the correct URL, the bbc.com/, and then a UK version of the article. Is this happening for anyone else? Should I leave this or delete it? 

Also, if there is no date modified, what should we enter for the code in the modified function? 

Thanks!

**Comment by mikeizbicki** [comment]
The other additional URLs are supposed to be added, and you should also verify those URLs as well.  You shouldn't have any blank `human_annotator` labels when you're done.

For the modified date, leave it blank if you can't find it anywhere.

**Comment by selina-28030** [comment]
For the bbc urls, I found a more specific date including the time for both the published and modified date in a script tag in the head, but I can't seem to access it.

**Comment by mikeizbicki** [comment]
That's a good catch, thanks!  I hadn't noticed that there were dates in the `script` tags.  

You should just ignore these dates and only look for dates outside of the `script` tags.  I'll adjust the python code to look into these tags myself.

**Comment by rayegleekel** [comment]
I've gotten all the URLs, except the https://www.bbc.com/news/world-asia-50640033. The path I have written is
```
//div[@class= "date date--v2"]/data-datetime
```
It isn't pulling any date though. 

Thanks!

**Comment by mikeizbicki** [comment]
@rayegleekel The code only gets a title if it can find a date, so that's why there's no title.

The `/`s separate tags, so you've written an xpath for getting `XXX` out of
```
<div class="date date--v2"><date-time>XXX</date-time></div>
```
You can use the `@` syntax to extract the attribute from a particular tag.  In this case, the date is not within an attribute though, so you can just drop the `data-datetime` from the end.

**Comment by rayegleekel** [comment]
@mikeizbicki thank you, I got it to work except it doesn't enter the info for the uk version of the URL. Do we need to add another xpath for the bbc uk hostname?

**Comment by mikeizbicki** [comment]
Yes, add the other xpath.
