### ISSUE TITLE
URLs reading FALSE where they shouldn't

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#34]
With the new code, a lot of my URLs are coming in golden.csv as FALSE now where they used to be TRUE and they do exist. I'll keep working on it, but I may need to zoom on Monday if you have any availability.

**Comment by mikeizbicki** [comment]
The url will get marked as `FALSE` if it contains 0 dates or more than 1 date.  You can use the `--verbose` flag when adding the urls to see exactly how many dates are getting added and which xpaths are matching.

I meet with other students from 8-9:30 on Monday, but I'd be available after that.

**Comment by rayegleekel** [comment]
The test cases that are failing when I run 
```
$python3 -m pytest
```
seem to be entries that are not mine (i.e. they have different human annotator entries). Is this something I need to solve?

Sounds good on Monday--I am still working but if issues keep arising that time works for a Zoom.

**Comment by mikeizbicki** [comment]
In the future you should ensure that all test cases pass, but for this week just submit once you've got your own test cases passing.

**Comment by rayegleekel** [comment]
Okay; why would others test cases be failing for me but not themselves? 

The only thing that is failing of my entries is for bloomberg.com hostname entries. But I don't have access to the site URLs as I don't have a subscription, so I can't see them. The code is outputting a "You are a robot" message for the titles of these entries in golden.csv. I made a note of this in my pull request. All else is good I believe. Thank you!
