### ISSUE TITLE
"File name too long" error

### ISSUE THREAD

**Issue by selina-28030** [mikeizbicki/metahtml#38]
When I was running this command,
```
selina$ cat urls/week2-selina | xargs python3 tests/test_golden.py --insert_urls
```
this error popped up
```
OSError: [Errno 63] File name too long: 'tests/.cache/https___arabic.rt.com_middle_east_1101738-%D8%A7%D9%84%D8%B5%D8%AD%D8%A9-%D8%A7%D9%84%D8%B3%D9%88%D8%B1%D9%8A%D8%A9-%D8%A5%D8%B5%D8%A7%D8%A8%D8%A7%D8%AA-%D9%83%D9%88%D8%B1%D9%88%D9%86%D8%A7-%D8%A7%D9%84%D9%85%D8%B3%D8%AC%D9%84%D8%A9-%D8%AD%D8%AA%D9%89-%D8%A7%D9%84%D9%8A%D9%88%D9%85-19-%D8%B4%D9%81%D9%8A-%D9%85%D9%86%D9%87%D8%A7-3-%D9%88%D8%AA%D9%88%D9%81%D9%8A%D8%AA-%D8%AD%D8%A7%D9%84%D8%AA%D8%A7%D9%86_cd8fbd6e'
```

**Comment by mikeizbicki** [comment]
I've uploaded a fix that prevents long filenames from being created in the cache folder.  I think it should fix this problem for you.

**Comment by selina-28030** [comment]
Thank you! When I tried running it again, there was an error with another link.
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='coronavirusnewslive.com', port=443): Max retries exceeded with url: /tag/ (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')")))
```

**Comment by mikeizbicki** [comment]
Hmm... my best guess based on a quick google is that you have an older version of openssl (the library responsible for handling webpage encryption) installed.  Just skip this url for now.

**Comment by rayegleekel** [comment]
I already have made xpath additions to my code but now am having the file name too long error with one of my URLs. Is there a way to pull the fix without loosing my added code for this week so far? Thanks!

**Comment by mikeizbicki** [comment]
The commit I added only effects the `tests/test_golden.py` file, so you might be able to run
```
$ git pull upstream master
```
and have everything work.  If that doesn't work, you'll have to redownload and copy and paste your changes.

**Comment by rayegleekel** [comment]
When I ran this command I got:
```
error: Your local changes to the following files would be overwritten by merge:
	tests/golden.csv
Please commit your changes or stash them before you merge.
Aborting
```
Will committing allow me to keep the progress I've made in golden.csv? I'm running the URL command:
```
$python3 tests/test_golden.py --insert 
```
 on individual hostnames, one at a time, and I have done about 25 hosts so far so I would have to re-run the command on all of those to get them back into golden.csv.

**Comment by mikeizbicki** [comment]
`golden.csv` contains lines from both versions of the file.  You will have to manually edit the file.

**Comment by rayegleekel** [comment]
I'm a bit confused. If I commit what I have done so far, should the command 
```
$git pull upstream master
```
work? I haven't manually entered the human_annotator column or edited the article names. So, I just mean getting the URLs I have already examined and written paths for into golden.csv. If I am not understanding correctly, I could zoom tomorrow if it would be easier as well.

**Comment by mikeizbicki** [comment]
What you describe can be done, but it will result in the same merge conflicts
that need to be fixed, so it's not going to help the situation.  It will also
result in a worse git history, so I'd prefer you not do it that way.  (A worse
git history would be okay if it actually saved you some work, but in this case
it won't.)

**Comment by rayegleekel** [comment]
Okay, I understand. So, I need to delete my repository and re-fork yours and re-clone?

Thanks!


________________________________

**Comment by mikeizbicki** [comment]
That will work.

Strictly speaking, it's not necessary though.  Cloning your repo and pulling
from mine would also work.

**Comment by rayegleekel** [comment]
I tried just cloning my repo but it didn't work as it said I already had that directory. Do you mean delete the folder locally and then reclone? Then should I then push my changes to github before I delete the folder? Thanks!
________________________________

**Comment by mikeizbicki** [comment]
You probably don't want to delete your previous repo, but yes, you would have to
rename it so that you can successfully run clone.
