### ISSUE TITLE
Stock Photo Websites

### ISSUE THREAD

**Issue by selina-28030** [mikeizbicki/metahtml#40]
Should websites like these be treated as not articles with blank title and date columns?

https://fr.freepik.com/vecteurs-premium/infographie-mers-cov-coronavirus-du-syndrome-respiratoire-du-moyen-orient_4917905.htm

https://www.canstockphoto.fr/3d-coronavirus-illustration-79065756.html

https://www.barewalls.com/art-print-poster/coronavirus-or-2019-ncov-cells-and_bwc77703158.html

**Comment by mikeizbicki** [comment]
Yes, treat them as not articles.

Good question.
