### ISSUE TITLE
XpathEvalError

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#41]
When I am running some URLs, I am getting the following error message, but I haven't yet even written an Xpath for the host name:

```
lxml.etree.XPathEvalError: Invalid expression
```
Up until now, I wouldn't get an error and the golden.csv entry would just read FALSE where it should read TRUE. But now, this error is coming up. Any idea what the issue is?  Thanks!

**Comment by mikeizbicki** [comment]
You can get this error if any of the xpaths have invalid syntax, not just the
xpaths for the particular domain.  (Whether the syntax is valid or not is not
related to the website's html, it is only a function of the xpath itself.)

All of the xpaths that are currently in the repo are valid, so either you have
accidentally changed one of those, or one of the xpaths you've added is
incorrect.

**Comment by rayegleekel** [comment]
Okay. All of the ones I have added successfully extract the info from their respective URLs. Would you recommend just commenting each addition I have made out? Thanks!
________________________________

**Comment by rayegleekel** [comment]
I checked them all and got the error to go away with the last URL I ran. Then, I ran the next one that I hadn't yet checked or written an Xpath for and the error message came back, which makes me think the error is occurring whenever I run a URL that I haven't written an Xpath for. Do you have later today or tomorrow to zoom quickly?
________________________________

**Comment by mikeizbicki** [comment]
I'm on zoom right now.

**Comment by rayegleekel** [comment]
I figured it out--I just updated my computer and for some reason caused an issue that appears to be fixed after I ran a command to re-configure my terminal after the update. Thank you!
________________________________
