### ISSUE TITLE
Zoom meeting

### ISSUE THREAD

**Issue by shashankvineet** [mikeizbicki/metahtml#42]
Will you be on zoom later today or tomorrow? I'd like to go over some errors I've been getting

**Comment by mikeizbicki** [comment]
I'm on zoom right now.

**Comment by selina-28030** [comment]
Are you still available this afternoon on zoom?

**Comment by mikeizbicki** [comment]
I can be available at 1pm today if that works.

**Comment by selina-28030** [comment]
Yes!
