### ISSUE TITLE
Discussion board being recognized as an article

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#44]
A discussion board is registering as an article and pulling the dates of people's posts/comments. Is there a way I can prevent this or is that something that has to be done in a different part of the code? Thanks!

**Comment by mikeizbicki** [comment]
Enter `FALSE` in the article column and `skip` in the `human_annotator` column.  That'll prevent the test case from being run, but let me know I need to look at that one myself to fix it.
