### ISSUE TITLE
Failing tests of others entries

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#46]
I have passed all but 6 test cases and the ones that are failing don't seem to be my additions for this weeks URLs as they have other names for human_annotator. Why would this be happening and how should I handle it? Thanks!

**Comment by mikeizbicki** [comment]
That's okay, you can just submit it as-is.  I think different versions of some of the libraries produce different results, so I have to go through and specify the library versions a bit more specifically.

**Comment by rayegleekel** [comment]
Okay, thanks! For some reason, 2 of my URLs (newsweek.com ) that are in my urls/week2-raye file are not appearing as entries in golden.csv. But, I ran the whole urls/week2-raye file after I removed the URLs that were giving an error (no page found, etc.) and I got no error so I know it finished running. Have you had this happen before?
