### ISSUE TITLE
Availability today

### ISSUE THREAD

**Issue by peter-dimitrov** [mikeizbicki/metahtml#50]
Hi Prof. Izbicki,

Will you be available to talk on zoom today?

**Comment by mikeizbicki** [comment]
Sorry, I was in other meetings and babysitting all day today.  I can meet at 1pm tomorrow (Tuesday).  Does that work?

**Comment by peter-dimitrov** [comment]
No problem, I could do 1:30 if that works, thanks Professor

**Comment by mikeizbicki** [comment]
I'm on right now, and I'll be on until 1, but I'll have to leave before 1:30.  If this time doesn't work today, we can do tomorrow.

**Comment by peter-dimitrov** [comment]
Got it, I will talk to you tomorrow then!

**Comment by peter-dimitrov** [comment]
Hi Prof., what time are you available today?

**Comment by mikeizbicki** [comment]
@peter-dimitrov Sorry for missing the appointment, we had to put our son down for a nap later today than I was expecting.  I'm on zoom right now.
