### ISSUE TITLE
Picking datetime between meta and body

### ISSUE THREAD

**Issue by shashankvineet** [mikeizbicki/metahtml#54]
As I had mentioned in our call last week, I was having issues with the timezone affecting the times of many of the articles. I realized that there was a different time listed in the metadata of the URLs as compared to the time listed in the body. The only difference between the two listed times lies in the timezone modification, which lies in the time listed in the body. In this case, which time do you suggest I pick?

**Comment by mikeizbicki** [comment]
If one has a timezone and the other doesn't, prefer the one with the timezone. 
Otherwise, prefer the one in the meta information.
