### ISSUE TITLE
Questions about inputting URLs

### ISSUE THREAD

**Issue by peter-dimitrov** [mikeizbicki/metahtml#6]
I have a few questions about inputting the URLs.

1.) Is there a command that we can run to double check that the xpaths we put in are correct?
2.) What if a URL didn't get its title put into the csv? Should we do it manually?
3.) If a date is wrong, do we manually change it?
4.) What if a domain (ex. bbc.com) has different xpaths for different pages? Do we put multiple 'bbc.com' entries into the timestamp.py file?
5.) For the commit message, hostname refers to a domain (Ex. BBC), right?

Thanks

**Comment by mikeizbicki** [comment]
Great questions.

> 1.) Is there a command that we can run to double check that the xpaths we put in are correct?

The final check of correctness is that when you run
```
$ python3 test/test_golden.py --insert_url XXX
```
then the `test/golden.csv` file is updated to include the correct dates.  You can also pass the `--verbose` option when inserting urls like so
```
$ python3 test/test_golden.py --verbose --insert_url XXX
```
which will output all the matched xpaths, but there's a lot of output here that can be hard to read.

> 2.) What if a URL didn't get its title put into the csv? Should we do it manually?

The title only gets added when a date is added; if there is no date, then there should be no title.  If there's ever a date without a title, then let me know so I can take a look personally.

> 3.) If a date is wrong, do we manually change it?

No, you should adjust the xpath until the date becomes correct.

> 4.) What if a domain (ex. bbc.com) has different xpaths for different pages? Do we put multiple 'bbc.com' entries into the timestamp.py file?

Yes.

> 5.) For the commit message, hostname refers to a domain (Ex. BBC), right?

Yes, but it should be `bbc.com` not `BBC`.

**Comment by peter-dimitrov** [comment]
Thank you, I have a few more questions. Firstly, every time I run the input_urls command, it adds ~40 blank lines to the beginning of the csv file. Is there any way to stop this from happening?

I am also having trouble with these last few URLs, and don't see where I went wrong with the xpaths. 

For https://www.bbc.com/news/world-asia-50640033:
```//div[@class="date date--v2"]```

For https://www.bbc.com/worklife/article/20200522-why-weve-created-new-language-for-coronavirus:
```//span[@class=author-unit__date]```

For https://carnegieendowment.org/experts/1322:
I don't see a date on this page, so I am confused about what we are meant to input.

For https://theintercept.com/drone-papers/target-africa/
https://theintercept.com/drone-papers/the-assassination-complex/
https://theintercept.com/drone-papers/the-kill-chain/:
```//span[@class="PostByline-date"]/span```

Hopefully somebody can shed some light on this. Thank you

**Comment by mikeizbicki** [comment]
> Thank you, I have a few more questions. Firstly, every time I run the input_urls command, it adds ~40 blank lines to the beginning of the csv file. Is there any way to stop this from happening?

This is likely also due to the windows incompatibilites that we talked about before.  Don't worry about it for now, but it should be fixed before I get you the next set of urls.

> I am also having trouble with these last few URLs, and don't see where I went wrong with the xpaths.
> 
> For https://www.bbc.com/news/world-asia-50640033:
> `//div[@class="date date--v2"]`

This matches too many different dates.  If an xpath matches more than 1 different date, then it will be marked as invalid and won't find anything.  If you use the `--verbose` option it will show you all the matched dates.

> For https://www.bbc.com/worklife/article/20200522-why-weve-created-new-language-for-coronavirus:
> `//span[@class=author-unit__date]`

You need quotation marks around the value `author-unit__date`.

> For https://carnegieendowment.org/experts/1322:
> I don't see a date on this page, so I am confused about what we are meant to input.

Things that don't have dates are not articles, and it is important that the program correctly identifies that they do not have dates.  Therefore, you should put `None` in the published date column.

> For https://theintercept.com/drone-papers/target-africa/
> https://theintercept.com/drone-papers/the-assassination-complex/
> https://theintercept.com/drone-papers/the-kill-chain/:
> `//span[@class="PostByline-date"]/span`

This works for me, so my best guess is that there's a typo in your hostname section.
