### ISSUE TITLE
Beginning week 4 URLs

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#72]
Should we not begin working on week 4 URLs until all the pull requests are merged so we don't get in the situation of having to re-pull from your repo after already making changes locally? Or is it not necessary to re-pull to incorporate the latest merges?

**Comment by mikeizbicki** [comment]
Go ahead and start working from the current commit.  You won't have to repull after I merge the remaining pull requests, I'll take care of that myself when you submit your pull request.
