### ISSUE TITLE
Abbreviated golden.csv file

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#73]
When I open golden.csv, it is only showing about 200 or so rows and there are only entries through domains that start with the letter "b". When I look at the code on your repo, golden.csv shows 1000+ rows, as it should and has before with me. Do you have any idea what could be going on here?

**Comment by mikeizbicki** [comment]
Hmm... that's weird, I have no idea what could have caused that.

The easiest fix would be to just reclone the repo.

**Comment by rayegleekel** [comment]
I did this and it went back to normal. Then, I ran my first URL and opened golden.csv and it reverted back to being messed up. After running my first URL , I got the error: 
```
Traceback (most recent call last):
  File "tests/test_golden.py", line 388, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 245, in insert_golden_tests
    writer.writerow(row)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 151, in _dict_to_list
    + ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: None
```
Could this have caused it? Thanks!

**Comment by mikeizbicki** [comment]
I'll be on zoom tomorrow starting at 1.

**Comment by rayegleekel** [comment]
Okay, thank you, I'll be on at 1pm! Your fix did solve my problem but I have a few other questions.
