### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by shashankvineet** [mikeizbicki/metahtml#74]
When I ran 

```
cat urls/week4-shashank | xargs python3 tests/test_golden.py --insert_urls

```

I get the following error:

```
downloading url= http://www.globalsecurity.org/military/world/iraq/najaf.htm ... done.
downloading url= http://www.gocertify.com/ ... done.
downloading url= http://www.gocertify.com/articles/ ... done.
downloading url= http://www.gocertify.com/articles/security-matters-malware-jumps-the-air-gap.html ... done.
Traceback (most recent call last):
  File "tests/test_golden.py", line 388, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 198, in insert_golden_tests
    meta = metahtml.parse(html, url)
  File "./metahtml/__init__.py", line 60, in parse
    meta_best, meta_all = parse_all(html, url, fast=True)
  File "./metahtml/__init__.py", line 21, in parse_all
    parser = lxml.html.fromstring(html)
  File "/Users/shashankvineet/Library/Python/3.7/lib/python/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/shashankvineet/Library/Python/3.7/lib/python/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

```

What exactly is going wrong here?

**Comment by mikeizbicki** [comment]
I think the problem is that the html for that url is not formatted correctly.  You should just delete that url from the list and re-add the rest of them.

I should probably also fix the parsing code so that it doesn't crash here, so leave a note in the pull request that this url crashes the program.

**Comment by shashankvineet** [comment]
Got it. I will do that!

**Comment by shashankvineet** [comment]
I am also getting the following error for a lot of the URLs:

```
Traceback (most recent call last):
  File "tests/test_golden.py", line 388, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 262, in insert_golden_tests
    recursively_added_urls=recursively_added_urls
  File "tests/test_golden.py", line 198, in insert_golden_tests
    meta = metahtml.parse(html, url)
  File "./metahtml/__init__.py", line 60, in parse
    meta_best, meta_all = parse_all(html, url, fast=True)
  File "./metahtml/__init__.py", line 21, in parse_all
    parser = lxml.html.fromstring(html)
  File "/Users/shashankvineet/Library/Python/3.7/lib/python/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/shashankvineet/Library/Python/3.7/lib/python/site-packages/lxml/html/__init__.py", line 764, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty

```

Should I delete them as well and make a note of it?

**Comment by shashankvineet** [comment]
I seem to be getting the above-mentioned error for all of the URLs now. Any idea what could be going wrong?

**Comment by mikeizbicki** [comment]
My two guesses are

1) The web pages simple don't exist anymore, so nothing gets downloaded, and that's why the `Document is empty`.  That seems unlikely to happen for that many webpages though.  If you visit them in the browser and they work, that means this can't be the problem.

2) somehow the `golden.csv` file got corrupted from that first `ValueError`.  Do you still get these errors if you try to insert these urls into a fresh clone?

**Comment by shashankvineet** [comment]
I'm still getting these errors even after having cloned your updated repo. I commented out the URLs that were causing the initial ValueError and then ran the cat command to insert the urls and it gives the ```lxml.etree.ParserError: Document is empty ``` error.

**Comment by shashankvineet** [comment]
When I pushed to GitHub this week's work, Travis seems to be giving me the following error for virtually every single entry:
```
ValueError: there are too many columns in the CSV file; the likely cause of this problem is either that you have added an extra comma (,) in the title of the webpage without putting the title in quotes "like, this"

```
I haven't added any titles that contain any commas and I haven't changed any of the existing titles. Any idea why it's giving me this error?

**Comment by mikeizbicki** [comment]
In the past, your workflow has sometimes added extra commas at the end of every
line somehow.  You can see this by opening up the `golden.csv` in a text editor,
and on the very first header line will end in `title,` instead of `title`. 
Running the command
```
$ sed -i 's/,$//' tests/golden.csv
```
will delete these extra commas.
