### ISSUE TITLE
Encyclopedia entries

### ISSUE THREAD

**Issue by selina-28030** [mikeizbicki/metahtml#76]
are encyclopedia entries articles?

ex: http://www.atlapedia.com/online/countries/iran.htm

**Comment by mikeizbicki** [comment]
Good question.

Label them as an article, but since there's no date, leave that blank, and it
will fail the test case.

**Comment by selina-28030** [comment]
Are dictionary entries not considered articles?

**Comment by mikeizbicki** [comment]
Treat them as articles just like the encyclopedia entries.
