### ISSUE TITLE
'tuple' error 

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/metahtml#77]
Hi Professor Izbicki,

I've started using LibreOffice. Now, the error that I'm receiving when I try to add a new URL is: 

`traceback (most recent call last):
  File "tests/test_golden.py", line 384, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 198, in insert_golden_tests
    meta = metahtml.parse(html, url)
  File "./metahtml/__init__.py", line 60, in parse
    meta_best, meta_all = parse_all(html, url, fast=True)
  File "./metahtml/__init__.py", line 25, in parse_all
    meta_best['timestamp_published'], meta_all['timestamp_published'] = timestamp.get_timestamp_published(parser, url, fast=fast)
  File "./metahtml/timestamp.py", line 395, in get_timestamp_published
    ( None, '//meta[@property="rnews:datePublished"]/@content' ),
TypeError: 'tuple' object is not callable
`

I'm not sure how to solve it given that this is a missing comma error, right?

Thanks,
Maxine

**Comment by mikeizbicki** [comment]
I think you're probably missing a comma at the end of one of your xpath lines. 
Look for either the line generating the error or the line above it.

(I've been stumped by this one a lot before!)
