### ISSUE TITLE
xargs issue

### ISSUE THREAD

**Issue by selina-28030** [mikeizbicki/metahtml#78]
when i'm running this command
```
cat urls/week4-selina | xargs python3 tests/test_golden.py --insert_urls
```
I get this error:
```
xargs: unterminated quote
```

**Comment by mikeizbicki** [comment]
hmm... this will happen if one of the urls has a `'` or `"` inside of it.  You'll have to figure out which one of the urls this is and remove it from the file.  Then you can add it manually by putting quotation marks around the full url when you add it.
