### ISSUE TITLE
Tripadvisor URLs added almost 1000 new lines 

### ISSUE THREAD

**Issue by peter-dimitrov** [mikeizbicki/metahtml#81]
I ran the following command:
```
cat URLS_FILE | xargs python3 tests/test_golden.py --insert_urls
```
and it was running for at least 10 minutes or so adding new URLs, and it added around 700-800 new lines to the golden.csv file (I believe a huge portion of these were tripadvisor URLs). Because none of the tripadvisor URLs were articles with dates, should I ignore them/remove them from golden.csv, or otherwise if I were to keep them, should I ignore changing the humanannotator and isArticle fields for these? It seems like a bit of a waste of time to go through all these lines to add these fields.

Thanks

**Comment by peter-dimitrov** [comment]
For context, it's many, many screens of this:

![image](https://user-images.githubusercontent.com/56900637/86294979-9faaa900-bbc3-11ea-9971-058218d0a732.png)

**Comment by mikeizbicki** [comment]
It looks like it's adding the same urls many time, but with `.com` replaced by `.de`,`.dk`,etc.  Do just the `.com` urls, leave the rest blank, and make a note in the pull request.  I'll go through and figure out what to do with the rest.
