### ISSUE TITLE
Data sites/ info pages

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#82]
Should sites with only data about a place or person in table format be counted as an article? (ex: https://www.unipage.net/en/18727/islamic_azad_university_natanz) 

Also, should sites with contact/location info about places be counted as articles? (ex: https://www.unhcr.org/islamic-republic-of-iran.html) 

Thanks!

**Comment by mikeizbicki** [comment]
Yes, both of those should be considered articles.

Basically, anything that has any content is an article, unless the content is
just links to other articles.

**Comment by rayegleekel** [comment]
Okay, thank you! Most of these have no date/time info, so they will all be entered as TRUE but with no title. I will make a note of which ones I do this for in my pull request.
