### ISSUE TITLE
Challenge with an xpath

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#85]
There is one URL: https://www.wionews.com/world/us-sanctions-4-petroleum-firms-linked-to-irans-quds-force-276442
that I can't get the xpath for. I have tried every combination I could think of and it just doesn't seem to be working. I'm not sure if I am missing something or the date just can't be extracted using an xpath. 

Should I manually change it to TRUE and just submit my pull request and just make a note of this? Or leave it as FALSE so it fails its test case? I can also zoom if you think you could provide me some direction in writing a successful xpath. 

Thanks so much!

**Comment by mikeizbicki** [comment]
Just manually enter the values so it fails the test case.  The data for the page
also is stored in the `json+ld` script format in the header, and so when I get
that working, it'll get this page without needing the xpath.
