### ISSUE TITLE
Expired Articles

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/metahtml#86]
If an article has been expired, should we still include it if there is a date and time listed?

**Comment by mikeizbicki** [comment]
Can you post the link?  I'm not sure what you mean by expired.

**Comment by maxinebaghdadi** [comment]
The link for the expired article is: https://japantoday.com/category/sports/olympics/Kim-Jong-Un-lookalike-provokes-N-Koreans

I also have a few more questions as to whether the following are considered articles: 

1) What should I do with 404 errors? 
2) How should I deal with videos? How should I deal with videos that have a transcript on the bottom? 
3) What should I do with: https://www.slideshare.net/SyedAqeelHaider/imam-khomeini? 
4) Are government websites with travel recommendations articles? https://www.smartraveller.gov.au/destinations/middle-east/iran
5) Is this an article? https://www.smashwords.com/books/view/218692

Sorry for the bulk of questions. Let me know if it's easier to hop on a call. 

Thank you!

**Comment by mikeizbicki** [comment]
Yes, the expired article is an article.  The way to think about it is that it is an article with just those 2 sentences.  The content of the sentences doesn't matter, just the fact that it has a title and something there.

1) skip 404

2) any page with a single "content" is an article, whether that content is a blurb of text, a video, or a video+text; it's only not an article if it is an index page containing/linking to many other articles

3) That's an article published on Feb 18, 2012

4) that's an article

5) that's an article
