### ISSUE TITLE
is_article column labeling

### ISSUE THREAD

**Issue by selina-28030** [mikeizbicki/metahtml#9]
If a url is mislabeled as an article, should I manually change it?

**Comment by mikeizbicki** [comment]
Yes, change it to `FALSE` if it's not an article.

**Comment by selina-28030** [comment]
Also, what should I do if a url is not working?

**Comment by mikeizbicki** [comment]
What do you mean by not working?

**Comment by selina-28030** [comment]
When I go to the [website](https://krdo.com/news/national-world/2020/04/21/south-korea-says-no-unusual-signs-detected-about-kim-jong-uns-health/), it says "Page Not Found."

**Comment by mikeizbicki** [comment]
Interesting... just skip it for now, and I'll figure out the best way to handle it later.  Pick a different article from that domain instead so there's still something from that domain in the tests.
