### ISSUE TITLE
Only date updated and not date published

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#91]
If the site only lists a last updated date, should we write the path to the date modified function or date published function? I wrote to the date modified and all the domains are still coming in as FALSE. Thanks!

**Comment by mikeizbicki** [comment]
You're correct: write the path to the date modified and put `TRUE` for an
article.  The current code requires a published date to be an article, so the
test case will fail, and I'll have to fix it in the code.

**Comment by rayegleekel** [comment]
Okay, thank you! Should I manually enter the modified date in addition to inputting TRUE? Also, for this particular URL, 100 or so entries enter into golden.csv. Should I leave them all? The differ just in the language of the site I believe.

**Comment by mikeizbicki** [comment]
Yes, enter the modified date as well.

That's a lot!  Just do one of the languages, and leave the rest with no
`human_anotator`.
