### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/metahtml#99]
I just saw your note about the rest of the files so I've pushed them all to my repo, but it won't let me submit a new pull request. I think that's because my previous one hasn't been merged yet. Do you see that?

**Comment by mikeizbicki** [comment]
A pull request is attached to a particular branch, and so whenever you add commits to a pull requested branch, it automatically adds them to the pull request.  So I can see them, and I'll take a look at it now.
